### ISSUE TITLE
span attributes "error" cannot be set in SpanBuilder

### ISSUE THREAD

**Issue by SergeyKanzhelev** [bogdandrutu/openconsensus#41] opened 2019-04-04 16:41 UTC
Creating an issue to confirm that we can safely ignore setting `error` status in `SpanBuilder`.

**Comment by yurishkuro** [comment] 2019-04-04 21:40
not ignoring it would be less surprising behavior

**Comment by SergeyKanzhelev** [comment] 2019-04-04 23:28
are there valid scenarios when you want to set `error` to `true` using `SpanBuilder`?

**Comment by SergeyKanzhelev** [comment] 2019-04-04 23:28
Do we need the way to do it for OpenFoo API surface?

**Comment by carlosalberto** [comment] 2019-04-05 16:58
@yurishkuro So the problem is with the new API, where you set an error directly on a `Span` through `setStatus()`, not through a tag (also, observe this is for the OT bridge only ;) ).

Maybe we could let the tag go in (`error`) for `SpanBuilder` and only do the proper `setStatus()` match when used for `Span`? This way we are **not** ignoring it at least.

(Logically speaking, I think a `Span` being built should never be marked right away as being error-ed).

**Comment by carlosalberto** [comment] 2019-04-15 20:18
Closing as #106 has been merged.

**Closed by carlosalberto** 2019-04-15 20:18 UTC
Labels: Agreed
